# Debe coincidir con el Project Key que creaste en localhost:9000
sonar.projectKey=personal
sonar.projectName=banking-api

# Carpeta con tu código fuente
sonar.sources=src

# Excluir node_modules y archivos de build
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.spec.ts,**/*.test.ts

# Cobertura (si usas Jest)
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.typescript.lcov.reportPaths=coverage/lcov.info

# Conexión al servidor local
sonar.host.url=http://localhost:9000
sonar.token=sqp_2cd5671144c571724e636e08875f7680217bd8b5
